# Generated by Django 5.1.3 on 2024-11-17 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customerprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='address',
        ),
    ]
